name: mkdocs

on:
  push:
    branches:
      - master
    paths:
      - "**.md"
      - "mkdocs.yml"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Python - Upgrade pip
        run: pip install --upgrade pip
      - name: Python - Install mkdocs
        run: pip install mkdocs mkdocs-gen-files
      - name: Python - Install mkdocs material theme
        run: pip install mkdocs-material
      - name: Python - Install mkdocs same-dir plugin
        run: pip install mkdocs-same-dir
      - name: Configure git as github-actions bot
        run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Publish docs
        run: mkdocs gh-deploy
