name: mkdocs

on:
  push:
    branches:
      - master
    paths:
      - "**.md"
      - "**.css"
      - "mkdocs.yml"
      - ".github/workflows/mkdocs_deploy.yml"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Fixes an issue where a commit is pushed to the pages branch outside of this workflow
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install mkdocs
        run:  |
          pip install --upgrade pip
          pip install mkdocs mkdocs-gen-files
          pip install mkdocs-material
          pip install mkdocs-material-extensions
          pip install mkdocs-redirects
          pip install mkdocs-same-dir
          pip install python-markdown-math
          pip install mkdocs-macro-plugin
      - name: Configure git as github-actions bot
        run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Publish docs
        run: mkdocs gh-deploy
